name: Validate YAML

on: [push]

jobs:
  yaml-verifications:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Kubeval
        uses: stefanprodan/kube-tools@v1
        with:
          kubectl: 1.23.0
          kustomize: 4.4.1
          helm: 2.17.0
          helmv3: 3.7.2
          kubeseal: 0.16.0
          kubeval: v0.16.1
          conftest: 0.28.3
          kubeconform: 0.4.12
          command: |
            echo "Run kubeval"
            kustomize build prometheus-operator/overlays/lab | kubeval --ignore-missing-schemas
      - name: Conftest
        uses: stefanprodan/kube-tools@v1
        with:
          kubectl: 1.23.0
          kustomize: 4.4.1
          helm: 2.17.0
          helmv3: 3.7.2
          kubeseal: 0.16.0
          kubeval: v0.16.1
          conftest: 0.28.3
          kubeconform: 0.4.12
          command: |
            echo "Run Conftest"
            kustomize build prometheus-operator/overlays/lab | conftest test --policy policy -